config/routes.rb
CollectiveCreativity::Application.routes.draw do
  resources :verses  
  

end

app/models/couple.rb
class Couple < ActiveRecord::Base
  include RailsSettings::Extend
  
  belongs_to :verse  
  attr_accessible :lines_number, :status
  
  has_many :lines
  has_many :variants, :through => :lines  
end

app/models/line.rb
class Line < ActiveRecord::Base
  include RailsSettings::Extend
  
  belongs_to :couple
  has_one :verse, :through => :couple
  attr_accessible :variants_number, :line_position
  
  has_many :variants  
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
  
  attr_accessible :rate, :dimension
end

app/models/ready_verse.rb
class ReadyVerse < ActiveRecord::Base
  belongs_to :user, :verse      
  attr_accessible :description, :text, :title
  
  ajaxful_rateable :stars => 10
  
end

app/models/setting.rb
class Setting < RailsSettings::CachedSettings
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :username
  validates_uniqueness_of :username
  
  has_many :verses
  has_many :ready_verses
  has_many :variants  
  ajaxful_rater
  
  def self.authenticate(username, password)
    user = User.find(:first, :conditions=>["username = ?", username])
    return nil if user.nil?
    return user if user.password==user.password
  end
  
  def verses_in_progress
    Verse.where(:status => "progress")
  end  
  
  def verses_involving    
    Variant.where("user_id"=>self.id).map(&:verse).uniq      
  end
end

app/models/variant.rb
class Variant < ActiveRecord::Base
  belongs_to :line
  belongs_to :user
  has_one :couple, :through => :line
  has_one :verse, :through => :couple
  attr_accessible :text
  
  ajaxful_rateable :stars => 10
end

app/models/verse.rb
class Verse < ActiveRecord::Base
  include RailsSettings::Extend  
  extend SettingReflection
  
  belongs_to :user  
  attr_accessible :description, :name, :status, :text
  
  attr_protected :id
  
  has_many :couples
  has_many :lines, :through => :couples
  has_many :variants, :through => :lines
  has_one :ready_verse  

  settings_attr_accessor :couple_num, :line_num
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/couple_controller.rb
class CoupleController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/verses_controller.rb
class VersesController < ApplicationController
  def index
    if params[:username]
      @verses = User.find(:username=>params[:username]).verses
    else
      @verses = Verse.all      
    end      
    
    respond_to do |format|
      format.html
      format.json { render :json => @verses }
    end
  end
  
  def show
    @verse = Verse.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @verse }
    end
  end
  def new
    @verse = Verse.new
    respond_to do |format|
      format.html
      format.json { render :json => @verse}
    end
  end
  def create
    user = User.find(:first, :conditions => ["username = ?", "jaromudr"])
    @verse = user.verses.create(params[:verse])
    respond_to do |format|
      if @verse
        format.html { redirect_to(@verse) } 
        format.json { render :json => @verse, :status => "created", :location => @verse }
      else
        format.html { render :action => "new" }
        format.json {render :json => @verse.error, 
                            :status => :unprocessable_entity}
      end
    end    
  end  
  def edit
    @verse = Verse.find(params[:id])
  end
  def update
    @verse = Verse.find(params[:id])
    respond_to do |format|
      if @verse.update_attributes(params[:verse])
        format.html  { redirect_to(@verse) }
        format.json  { head :no_content }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @post.errors,
                              :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @verse = Verse.find(params[:id])
    @verse.destroy
    respond_to do |format|
      format.html { redirect_to verses_url }
      format.json { head :no_content }
    end
  end      
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couple_helper.rb
module CoupleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/verse_helper.rb
module VerseHelper
end

app/helpers/verses_helper.rb
module VersesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CollectiveCreativity</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/verses/_form.html.erb
<%= form_for(@verse) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="settings">
  	<div class="field">
  		<%= f.label :couple_num  %>
  		<%= f.text_field :couple_num  %>  		
  	</div>  	
  	<div class="field">
  		<%= f.label :line_num  %>
  		<%= f.text_field :line_num  %>  		
  	</div>  	
  </div>      
  <div class="actions">
    <%= f.submit %>
  </div> 
  
<% end %>

app/views/verses/edit.html.erb
<h1>Edit verse</h1>
<%= render 'form' %>
<%= link_to 'Show', @verse %> |  
<%= link_to 'Back', verses_path %>

app/views/verses/index.html.erb
<div class="verses">
	<% @verses.each do |verse| %>
	<div class="verse">
		<%= verse.name %>(<%= verse.user.username %>)<br/>
		<%= verse.description %><br/>
		Settings - <%= verse.couple_num %>|<%= verse.line_num %>
		<%= link_to 'Show', verse %> |
		<%= link_to 'Edit', edit_verse_path(verse) %> | 
		<%= link_to 'Remove', verse, :method => :delete %>
	</div>
	<% end %>
	<%= link_to "New verse", new_verse_path  %>
</div>

app/views/verses/new.html.erb
<h1>New verse</h1>
<%= render 'form' %> 
<%= link_to 'Back', verses_path %>

app/views/verses/show.html.erb
<div class="verse">
	<header>
		<div class="name">
			<%= @verse.name %>(<%= @verse.user.username %>)
		</div>
		<div class="description">
			<%= @verse.description %>
		</div>		
	</header>
	
	<div class="couples">
		<% @verse.couples.each do |couple| %>
		<div class="couple">
			<% couple.lines.each do |text_line| %>
			<div class="text_line">
				<% text_line.variants.each do |variant| %>
					<div class="text_line_variant_block">
						<span>
							<%= variant.text %>
						</span>
						<div class="info">
							Author: <%= variant.user.username %>
						</div>
					</div>
				<% end %>	
			</div>			
			<% end %>
		</di>		
		<% end %>
	</div>
</div>